### ISSUE TITLE
User Stories for Iteration 5 and Iteration 6 for the project report

### ISSUE THREAD

**Issue by vidhi281796** [ygoralmeida1993/Group-4-project#17]
Solved.

**Comment by haocencol** [comment]
@vidhi281796 what user story is this?  For which user role?

**Comment by haocencol** [comment]
@vidhi281796 for which iteration/sprint are we talking about for this user story?

**Comment by haocencol** [comment]
@vidhi281796 each story corresponds to one Github issue and each story should have two or more tasks.

**Comment by vidhi281796** [comment]
The user stories for iteration 5 and iteration 6 .

**Comment by Hirvashah2112** [comment]
Hello,

User stories for iteration 5 and iteration 6
Regarding cost calutation for different mode of transportation.
Will include it in detail
