### ISSUE TITLE
A User can get an estimate of the cost of using personal vehicle mode of transportation.

### ISSUE THREAD

**Issue by haocencol** [ygoralmeida1993/Group-4-project#2]

**Comment by haocencol** [comment]
#5 #4

**Comment by haocencol** [comment]
#6

**Comment by patelshikha** [comment]
https://api.collectapi.com/gasPrice/turkeyGasoline?city=istanbul&district=kadikoy
I found this Gas API which accepts City name and district name as parameters

**Comment by patelshikha** [comment]
https://www.eia.gov/opendata/bulkfiles.php

This one is for the US.

**Comment by vidhi281796** [comment]
The user story has been added to the project report.
