### ISSUE TITLE
 Extracting required data from the gas API for implementation for calculating budget trip

### ISSUE THREAD

**Issue by vidhi281796** [ygoralmeida1993/Group-4-project#23]

**Comment by patelshikha** [comment]
http://devapi.mygasfeed.com/
I implemented this RESTAPI. 
This is the response
{"country":"United States","zip":"14131","reg_price":"3.95","mid_price":"N\/A","pre_price":"4.23","diesel_price":"4.35","reg_date":"7 years ago","mid_date":"7 years ago","pre_date":"7 years ago","diesel_date":"7 years ago","address":"2560 Youngstown Lkpt Rd","diesel":"1","id":"11605","lat":"43.238312","lng":"-78.908707","station":null,"region":"New York","city":null,"distance":"39.7 miles"}

**This not useful as the response is only for United States**

**Comment by patelshikha** [comment]
I am trying different API

**Comment by patelshikha** [comment]
"https://api.collectapi.com/gasPrice/canada"
**For this one we get 100 request free**

**Comment by Shirali23** [comment]
@patelshikha I found some API as follows:
1) https://ethgasstation.info/json/ethgasAPI.json
2)https://ethgasstation.info/
GET Request
https://ethgasstation.info/json/ethgasAPI.json

**Comment by patelshikha** [comment]
Successfully getting this respone :

{"success":true,"result":[{"name":"Alberta","currency":"usd","gasoline":"0.99"},{"name":"British Columbia","currency":"usd","gasoline":"1.32"},{"name":"Manitoba","currency":"usd","gasoline":"0.97"},{"name":"New Brunswick","currency":"usd","gasoline":"1.16"},{"name":"Newfoundland and Labrador","currency":"usd","gasoline":"1.24"},{"name":"Nova Scotia","currency":"usd","gasoline":"1.11"},{"name":"Ontario","currency":"usd","gasoline":"1.10"},{"name":"Prince Edward Island","currency":"usd","gasoline":"1.16"},{"name":"Quebec","currency":"usd","gasoline":"1.17"},{"name":"Saskatchewan","currency":"usd","gasoline":"1.06"}]}
