### ISSUE TITLE
Implementation of Weather API (Mode of transportation - Car)

### ISSUE THREAD

**Issue by Hirvashah2112** [ygoralmeida1993/Group-4-project#26]

**Comment by Pujaholy** [comment]
I have implemented the DarkSky API for weather feeds. I have opened a new branch "new weather API". The older weather API gave feed for only one day. Weather2020 gave no feeds for Toronto locations. Other weather APIs like AccuWeather were not free. DarkSky fits the best as it gives feeds for free atleast upto 8 days.
Weather API implementation is complete and successful.
