### ISSUE TITLE
Log into the system using Google or Facebook credentials

### ISSUE THREAD

**Issue by ygoralmeida1993** [ygoralmeida1993/Group-4-project#32]

**Comment by Hirvashah2112** [comment]
@ygoralmeida1993 may I know the progress of this task?

**Comment by ygoralmeida1993** [comment]
Sure, I'm going to close this issue since I have been told that this functionality is useless. Print with evidence bellow:

![image0](https://user-images.githubusercontent.com/56020308/75843370-fda7bb00-5da0-11ea-8d22-3e17f6edc866.png)

**Comment by Hirvashah2112** [comment]
@ygoralmeida1993 may be you have understood in a different manner. It was not the important part because the main functionality of our project was remaining so we needed to focus on that with high priority. That’s why you were told not to do it at that time

**Comment by Hirvashah2112** [comment]
@ygoralmeida1993 so now as main features are almost been executed now we need to implement this part.
So let me know if you want to do this part otherwise I can start working on it

**Comment by ygoralmeida1993** [comment]
Ok, then I will start working on it

**Comment by ygoralmeida1993** [comment]
I have implemented login using Facebook and Google. It was committed and pushed into branch FacebookAndGoogleLogin. I will wait for you guys to check it so I can close the issue.

**Comment by patelshikha** [comment]
> Sure, I'm going to close this issue since I have been told that this functionality is useless. Print with evidence bellow:
> 
> ![image0](https://user-images.githubusercontent.com/56020308/75843370-fda7bb00-5da0-11ea-8d22-3e17f6edc866.png)

@ygoralmeida1993 You were not working on any of the issue that is why we asked for implementing the API first. We all can have hangouts meeting if you have any doubt related to the project.

**Comment by patelshikha** [comment]
@ygoralmeida1993 I checked your code. It is partially implemented. I **can not pass login** screen with google sign in. After signing through google the user must pass the login screen.  Can you complete it by Thursday or someone else can work on it.
@haocencol

**Comment by patelshikha** [comment]
@Hirvashah2112 you can work on this if not done by Thursday.

**Comment by ygoralmeida1993** [comment]
I have fixed the google sign in button

**Comment by vidhi281796** [comment]
@ygoralmeida1993 the code

**Comment by vidhi281796** [comment]
@ygoralmeida1993 I checked the code but it is not working properly as I am not able to pass the login screen and also for the facebook I am getting error

**Comment by patelshikha** [comment]
@ygoralmeida1993 Can you tell me what problem are you facing? I can help you out. 
Firebase gives permission for using google and Facebook login. You need to enable it on firebase. You can find the documentation.

**Comment by patelshikha** [comment]
@ygoralmeida1993  https://firebase.google.com/docs/auth/android/facebook-login
This is for your reference. You just need to follow these steps.
