### ISSUE TITLE
Creating an algorithm for calculating the budget of trip based on weather and gas price. (Transportation mode:car) 

### ISSUE THREAD

**Issue by vidhi281796** [ygoralmeida1993/Group-4-project#33]
The calculation of the trip budget will be based on various filters which can be type of weather snowy,windy,sunny etc.
It would also depend on gas price ,type and brand of car.

**Comment by vidhi281796** [comment]
I am trying to find out how temperature affects the fuel consumption of car.

According to official fuel economy website ,a conventional gasoline car's gas mileage is about 12% lower at 20°F than it would be at 77°F. It can drop as much as 22% for very short trips (3 to 4 miles).
Reference:
https://www.fueleconomy.gov/feg/coldweather.shtml

**Comment by vidhi281796** [comment]
I am also searching for any dataset which can be used for getting the mileage of car based on car type and brand.
Below link provides the csv file for the car mileage based on various filters.

https://www.fueleconomy.gov/feg/download.shtml

**Comment by ygoralmeida1993** [comment]
I am also looking for this API, and so far this is the only one that I found. The problem is: it only brings the values using the US forms of measurement, such as gallon, miles, etc. Also it only has vehicles that exist in the US, so if we are in another part of the world, it would be a problem to find the vehicle that the person will use. Another thing is, in our application, we only allow the user to chose between car categories and not car models. Why do we have to calculate the cost based on the car model and not car category?

**Comment by vidhi281796** [comment]
This is not API,actually I am searching for the data first and for our project ,to make it more realistic I am trying to add more filters ,I am searching for car models.

**Comment by patelshikha** [comment]
**I filtered and stored required parameters from responses of weather API and Gas API:**
Following is for Weather API:
1) Weather Icon (Snow, Windy etc...)
2) Maximum temperature
3)Minimum temperature
4)Wind Speed

Following is for Gas API:
1) Province Name
2) Gasoline price
3) Currency

**Comment by patelshikha** [comment]
@vidhi281796  I successfully retrived the data from JSON Array. Now you can start implementing the logic for calculating the transportation cost (car)

**Comment by vidhi281796** [comment]
![CalculatingMileage](https://user-images.githubusercontent.com/60582267/75744043-13ee4200-5ce1-11ea-80f9-8e368c6c5063.jpg)

**Comment by vidhi281796** [comment]
![Travel Cost](https://user-images.githubusercontent.com/60582267/75744057-236d8b00-5ce1-11ea-8f34-1597ed655c0e.jpg)

**Comment by vidhi281796** [comment]
I have created an algorithm for calculating the mileage .
![CalculatingMileage](https://user-images.githubusercontent.com/60582267/75754408-b2d36800-5cfa-11ea-8c57-74edb19acad9.jpg)

**Comment by vidhi281796** [comment]
Formula for travel cost.
![Travel Cost](https://user-images.githubusercontent.com/60582267/75754484-d0a0cd00-5cfa-11ea-82be-a845a2e6bd0e.jpg)

**Comment by vidhi281796** [comment]
This task has been completed
