### ISSUE TITLE
Creating an Logic and flow for calculating the budget of trip based on flight API and Places Data. (Transportation mode: Flight)

### ISSUE THREAD

**Issue by Hirvashah2112** [ygoralmeida1993/Group-4-project#36]

**Comment by patelshikha** [comment]
@Hirvashah2112 You will be adding flight price + cost for the place where the user wants to travel, right?

**Comment by Hirvashah2112** [comment]
@patelshikha i have decided flow for total cost if user is choosing flight as a mode of transportation.
I am searching for some other API as well 
So I will share that flow soon

**Comment by Hirvashah2112** [comment]
@georgelele1 @ygoralmeida1993 @patelshikha @vidhi281796 @Shirali23 @Pujaholy 
![IMG-7465](https://user-images.githubusercontent.com/51724095/76053817-74c58680-5f3c-11ea-96a1-b89eee9d1160.jpg)

**Comment by Hirvashah2112** [comment]
** FOR RELEASE 04**

@georgelele1 @ygoralmeida1993 @patelshikha @vidhi281796 @Shirali23 @Pujaholy 

![IMG-7464](https://user-images.githubusercontent.com/51724095/76053840-8eff6480-5f3c-11ea-96f8-6f0187326023.jpg)

![IMG-7465](https://user-images.githubusercontent.com/51724095/76053858-a6d6e880-5f3c-11ea-8bfc-50f7e2064261.jpg)

Please read this notes and give your suggestions.

**Comment by Hirvashah2112** [comment]
@georgelele1 @ygoralmeida1993 please let me know on which part you are willing work on for above flow. and around when will you be able to complete that task?
I am working on API to get the places details.
