### ISSUE TITLE
Small issue on git-hub. Related to iteration. Read comment below.

### ISSUE THREAD

**Issue by patelshikha** [ygoralmeida1993/Group-4-project#39]
@ygoralmeida1993 @Hirvashah2112 @Shirali23 @Pujaholy @vidhi281796 

I can see some of you have assigned your task in iteration 1 or 2.
**Currently, we are working on iteration 5 and 6**
**So please assign your task in iteration  5 or 6.**

**Comment by vidhi281796** [comment]
We made a mistake in previous comment. Sorry for that.

**Comment by ygoralmeida1993** [comment]
I have already fixed this issue in my part

**Comment by Pujaholy** [comment]
Issue is fixed
