### ISSUE TITLE
Creating UI for getting inputs for destination, date and no. of passenger (Mode of transportation car)

### ISSUE THREAD

**Issue by patelshikha** [ygoralmeida1993/Group-4-project#44]

**Comment by patelshikha** [comment]
Implementing Material-Calendar for date field
**com.applandeo:material-calendar-view:1.0.1**

**Comment by vidhi281796** [comment]
@patelshikha I added this date picker.

![Screenshot_1583392679](https://user-images.githubusercontent.com/60582267/75957274-afb9b280-5e87-11ea-8a8f-5a72262f1e5d.png)

**Comment by patelshikha** [comment]
Implemented logic for **getting dates from calendar**
Added **Auto Complete Text View** for Destination
Implemented logic for **increment and decrement using switch case**
Changed the old view with card view, date picker, auto complete edit text



![Screenshot_1583394916](https://user-images.githubusercontent.com/29619919/75959742-ca425a80-5e8c-11ea-9a27-905c70ac14f6.png)
