### ISSUE TITLE
Investigate publicly available API for gas prices.

### ISSUE THREAD

**Issue by haocencol** [ygoralmeida1993/Group-4-project#5]
#2

**Comment by haocencol** [comment]
@georgelele1 I found this gas api...I heard that you found another one, please share.

**Comment by patelshikha** [comment]
https://www.globalpetrolprices.com/api_gpp_cities.php?cts=2022&ind=gp&prd=latest&uid=1672&uidc=9e93f188bf4b9161ef0de2a7bb151b8d
This is the another API but I have not found any documentation for this. Still working on it

**Comment by patelshikha** [comment]
"https://api.collectapi.com/gasPrice/canada"

The response is as follows:
{
"success": true,
"result": [
{
"name": "Alberta",
"currency": "usd",
"gasoline": "0.98"
},
{
"name": "British Columbia",
"currency": "usd",
"gasoline": "1.29"
}
]
}

**Comment by patelshikha** [comment]
https://www.eia.gov/opendata/bulkfiles.php

This one is for the US.

**Comment by patelshikha** [comment]
**list of gas price**
**_/locations/pricehistory/(station id)/apikey.json?callback=?_**

In this one, we do need a station id for the **nearby station** using  _**/stations/radius/(Latitude)/(Longitude)/(distance)/(fuel type)/(sort by)/apikey.json?callback=?**_

We will get a gas price for the nearby gas station by implementing 2 API

http://www.mygasfeed.com/
