### ISSUE TITLE
Flight mode of transportation

### ISSUE THREAD

**Issue by patelshikha** [ygoralmeida1993/Group-4-project#50]
What is the progress for implementing the flight mode transportation **budget and UI** for iteration 6, as the release 3 is due by Sunday, March 8?
  @ygoralmeida1993 @Hirvashah2112 @georgelele1 @Pujaholy @Shirali23 @vidhi281796

**Comment by Hirvashah2112** [comment]
@patelshikha We have included flight API extraction for release 3 as of now. We will include implementation and calculation in release 4
