### ISSUE TITLE
UI for personal vehicle mode of transportation (design).

### ISSUE THREAD

**Issue by haocencol** [ygoralmeida1993/Group-4-project#6]
Draw pic of design and drag and drop into comment box.

**Comment by haocencol** [comment]
#2

**Comment by patelshikha** [comment]
@ygoralmeida1993 Could you share mock UI for this screen?

**Comment by ygoralmeida1993** [comment]
While trying to implement the UI for personal vehicle I have found some issues. I can't go past the login screen when running the application because I do not have access to the database, therefore the application cannot store or retrieve the information necessary to log into the application.

**Comment by ygoralmeida1993** [comment]
I have just pushed into master branch the UI for personal transportation

**Comment by patelshikha** [comment]
@ygoralmeida1993 
![ygor_UI](https://user-images.githubusercontent.com/29619919/75508195-5518e600-59b1-11ea-834c-74b18bd8975a.png)


Is this the one you implemented?
Because I can not see this UI with two Edit text in our project.

**Comment by ygoralmeida1993** [comment]
Ok, so what fields should be contained in this UI? Where in the documentation are the requirements specified? With no documentation describing what each interface should have, it is a little complicated to understand what the requirements are.

**Comment by patelshikha** [comment]
@ygoralmeida1993 You can add these fields in the UI which is already created by me

**Comment by patelshikha** [comment]
@ygoralmeida1993 Do not make a whole new project for the UI. Add in the project we all are working in. The latest branch is firebase.

**Comment by patelshikha** [comment]
@ygoralmeida1993 @haocencol  I completed the views for car mode transportation. So I am assigning myself to the issue.

**Comment by patelshikha** [comment]
![Screenshot_1583217735](https://user-images.githubusercontent.com/29619919/75944936-e8955f80-5e66-11ea-86a3-01bf3d85e088.png)

**Comment by patelshikha** [comment]
![CollapseView1](https://user-images.githubusercontent.com/29619919/75944950-f4812180-5e66-11ea-8552-d3766816e93b.png)

**Comment by patelshikha** [comment]
![CollapseView2](https://user-images.githubusercontent.com/29619919/75945011-167aa400-5e67-11ea-8497-0e3d18171ba5.png)

**Comment by patelshikha** [comment]
![CollapseView3](https://user-images.githubusercontent.com/29619919/75945034-27c3b080-5e67-11ea-9725-bcee72b70074.png)
